## **MARKETING** ##

## **OMD S.A.S** ##

Para llevar a cabo este analisis empesaremos a cargar el dataset encontrado

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd
data_csv=pd.read_csv("marketing.csv")
data_csv.head(10)

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,16174.0,6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,11566.0,5.61,New York,German,116,7523,7,Fashionistas,2021-01-02
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,10200.0,7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,12724.0,5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,16452.0,6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05
5,6,DataTech Solutions,Display,All Ages,15 days,Instagram,0.07,9716.0,4.36,New York,German,100,1643,1,Foodies,2021-01-06
6,7,NexGen Systems,Email,Women 35-44,60 days,Website,0.13,11067.0,2.86,Los Angeles,Spanish,817,8749,10,Tech Enthusiasts,2021-01-07
7,8,DataTech Solutions,Search,Men 18-24,45 days,Google Ads,0.08,13280.0,5.55,Los Angeles,Mandarin,624,7854,7,Outdoor Adventurers,2021-01-08
8,9,Alpha Innovations,Social Media,Women 35-44,15 days,Facebook,0.09,18066.0,6.73,Chicago,German,861,1754,6,Tech Enthusiasts,2021-01-09
9,10,TechCorp,Email,Women 35-44,15 days,Instagram,0.09,13766.0,3.78,Los Angeles,English,642,3856,3,Tech Enthusiasts,2021-01-10

# **LIMPIEZA DE DATOS** #

**Se realizo una limpieza en **Acquisition_Cost** eliminando el simbolo de dolar y comas que pudieran hacer daño a la hora de hacer operaciones**

In [6]:
data_csv['Acquisition_Cost'] = data_csv['Acquisition_Cost'].replace('$', '').replace(',', '').astype(float)
data_csv['Acquisition_Cost'].head()

0    16174.0
1    11566.0
2    10200.0
3    12724.0
4    16452.0
Name: Acquisition_Cost, dtype: float64

**Se eliminaron duplicados que habian en campain_ID**

In [8]:
data_csv= data_csv.drop_duplicates(subset='Campaign_ID', keep='first') 
data_csv.head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,16174.0,6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,11566.0,5.61,New York,German,116,7523,7,Fashionistas,2021-01-02
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,10200.0,7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,12724.0,5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,16452.0,6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05

Por ultimo decido guardar el archivo ya limpio y comprimirlo para que en vez de trabajar con 200 mil datos trabajar con 5000 datos asi al momento de hacer graficos se pudieran visualizar de una mejor manera

In [10]:
data_csv_5000 = data_csv.head(5000)  
data_csv_5000.to_csv('marketing_5000.csv', index=False, encoding='utf-8')

data_csv.to_csv("marketing.csv", index=False)
print("¡Archivo limpiado y guardado con éxito!")
print(f"Archivo guardado con {len(data_csv_5000)} registros")

¡Archivo limpiado y guardado con éxito!
Archivo guardado con 5000 registros

In [11]:
data_csv=pd.read_csv("marketing_5000.csv")
data_csv.head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,16174.0,6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,11566.0,5.61,New York,German,116,7523,7,Fashionistas,2021-01-02
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,10200.0,7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,12724.0,5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,16452.0,6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05

## **ANALISIS POR COLUMNAS** ##

In [13]:
clases_unicas, conteos = np.unique(data_csv['Company'], return_counts=True)
for clase, count in zip(clases_unicas, conteos):
    print(f"{clase}: {count}")

Alpha Innovations: 969
DataTech Solutions: 1001
Innovate Industries: 1025
NexGen Systems: 985
TechCorp: 1020

In [14]:
data_csv['Conversion_Rate'].describe()

count    5000.000000
mean        0.079822
std         0.040801
min         0.010000
25%         0.050000
50%         0.080000
75%         0.110000
max         0.150000
Name: Conversion_Rate, dtype: float64

In [16]:
data_csv['Acquisition_Cost'].describe()

count     5000.000000
mean     12521.832400
std       4359.636687
min       5000.000000
25%       8772.000000
50%      12572.000000
75%      16258.750000
max      19999.000000
Name: Acquisition_Cost, dtype: float64

In [25]:
data_csv['ROI'].describe()

count    5000.000000
mean        5.029228
std         1.731616
min         2.000000
25%         3.530000
50%         5.060000
75%         6.500000
max         8.000000
Name: ROI, dtype: float64

In [27]:
data_csv['Clicks'].describe()

count    5000.000000
mean      547.062800
std       257.843722
min       100.000000
25%       328.000000
50%       544.000000
75%       771.250000
max      1000.000000
Name: Clicks, dtype: float64

In [29]:
data_csv['Impressions'].describe()

count    5000.000000
mean     5520.930600
std      2608.516866
min      1000.000000
25%      3253.000000
50%      5552.000000
75%      7774.250000
max      9999.000000
Name: Impressions, dtype: float64

In [31]:
data_csv['Engagement_Score'].describe()

count    5000.00000
mean        5.47960
std         2.87361
min         1.00000
25%         3.00000
50%         5.00000
75%         8.00000
max        10.00000
Name: Engagement_Score, dtype: float64